version: "3"

services:
  # MongoDB database
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=5g-ran-portal
    networks:
      - 5g-network

  # Prometheus monitoring
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - 5g-network
    # Add this line for DNS resolution with host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Grafana visualization
  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./config/grafana/provisioning/dashboards/5g-dashboard.json:/var/lib/grafana/dashboards/5g-dashboard.json:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=5s
    depends_on:
      - prometheus
    networks:
      - 5g-network

volumes:
  mongodb_data:
  grafana_data:

# Add a custom network for all services
networks:
  5g-network:
    driver: bridge
